
// ApplicationCd
export const APPL_CD = {
  OVERTIME: 1,
  IRREGULAR: 2,
  ATTENDANCE_DETAIL: 3,
  LEAVE: 4,
  SUBSTITUTE_HOLIDAY: 5,
  LATE: 6,
  LEAVE_EARLY: 7,
  MANTATORY_PAID_LEAVE_CANCEL: 8,
  LONG_IRREGULAR: 9,
};
